services:
  - type: web
    name: my-nest-api
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
